// import Project from "@/types/Project";

// const topics: Project[] = [
//   {
//     topic: "Pilpres #2",
//     timeframe: "24 December 2023 – 30 December 2023",
//     keyword: "“Prabowo”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Pilpres #4",
//     timeframe: "24 December 2023 – 30 December 2023",
//     keyword: "“Ganjar”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",

//   },
//   {
//     topic: "Pilpres #3",
//     timeframe: "24 December 2023 – 30 December 2023",
//     keyword: "“Ganjar”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Digital Marketing #1",
//     timeframe: "1 December 2023 – 2 December 2023",
//     keyword: "“Tokopedia”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Digital Marketing #2",
//     timeframe: "1 December 2023 – 2 December 2023",
//     keyword: "“Shopee”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
//   {
//     topic: "Penyebaran Covid-19",
//     timeframe: "21 November 2023 – 21 December 2023",
//     keyword: "“Covid”",
//     country: "Indonesia",
//     countTweet: 20000,
//     detail: "See Analyst",
//   },
// ];

// export default topics;